name: CommunityMarket CI with maven
run-name: ${{ github.actor }} is testing Community Market API 🚀
on: [push]
steps:
  - uses: actions/checkout@v3
  - name: Set up JDK 11
    uses: actions/setup-java@v3
    with:
      java-version: '11'
      distribution: 'adopt'
  - name: Build with Maven
    run: mvn --batch-mode --update-snapshots package

