name: CommunityMarket CI with maven
run-name: ${{ github.actor }} is testing Community Market API 🚀
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Set up Java and Maven
        uses: actions/setup-java@v2
        with:
          java-version: 17

